### ISSUE TITLE
Error: No username provided

### ISSUE THREAD

**Issue by quartopianodesign** [niklasravnsborg/grunt-sync-deploy#3]
hi, 
launching the task returns an error:

Running "syncdeploy:main" (syncdeploy) task
Error: No username provided

Any suggestions?
Thank's

**Comment by niklasravnsborg** [comment]
Sure! Make sure you use the correct target (`grunt deploy --config=staging`) and to give the config your username.

For further assistance send me your Gruntfile. ☺️

**Comment by quartopianodesign** [comment]
server:project1 alessandromoschetti$ grunt deploy --config=production
Warning: Task "deploy" not found. Use --force to continue.

Aborted due to warnings.

and 

server:project1 alessandromoschetti$ grunt deploy --config=staging
Warning: Task "deploy" not found. Use --force to continue.

Aborted due to warnings.

this is a simple Gruntfile.js

module.exports = function(grunt) {

require('load-grunt-tasks')(grunt);
  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    uglify: {
      build: {
        src: ['js/libs/*.js', 'js/global.js' ],// Dictionary of files
        dest: 'js/build/global.min.js' // 'destination': 'source'
      }
    },

   syncdeploy: {
    main: {
      cwd: 'images/',
      src: ['**/*']
    }
  },
  deployInfo: grunt.file.readJSON('deploy_info.json'),
  sshconfig: {
  production: {
    host: '<%= deployInfo.host %>',
    port: '<%= deployInfo.port %>', // optional
    username: '<%= deployInfo.username %>',
    password: '<%= deployInfo.password %>',
    deployTo: '<%= deployInfo.deployTo %>'
  }
},
    sass: {                              // Task
   dist: {                            // Target
     options: {                       // Target options
       style: 'compressed'
     },
     files: {                         // Dictionary of files
       'css/build/global.css': 'css/global.scss'
     }
   }
 }
  });



  // Load the plugin that provides the "uglify" task.
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-sync-deploy');
  // Default task(s).
  grunt.registerTask('default', ['uglify', 'sass', 'deploy']);

};

**Comment by niklasravnsborg** [comment]
Try this:

```js
module.exports = function(grunt) {
	require('load-grunt-tasks')(grunt);
	// Project configuration.
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		uglify: {
			build: {
				src: ['js/libs/*.js', 'js/global.js'], // Dictionary of files
				dest: 'js/build/global.min.js' // 'destination': 'source'
			}
		},
		syncdeploy: {
			main: {
				cwd: 'images/',
				src: ['**/*']
			}
		},
		deployInfo: grunt.file.readJSON('deploy_info.json'),
		sshconfig: {
			production: {
				host: '<%= deployInfo.host %>',
				port: '<%= deployInfo.port %>', // optional
				username: '<%= deployInfo.username %>',
				password: '<%= deployInfo.password %>',
				deployTo: '<%= deployInfo.deployTo %>'
			}
		},
		sass: { // Task
			dist: { // Target
				options: { // Target options
					style: 'compressed'
				},
				files: { // Dictionary of files
					'css/build/global.css': 'css/global.scss'
				}
			}
		}
	});
	// Load the plugin that provides the "uglify" task.
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-sass');
	grunt.loadNpmTasks('grunt-sync-deploy');
	// Default task(s).
	grunt.registerTask('default', ['uglify', 'sass']);
	grunt.registerTask('deploy', ['syncdeploy']);
};
```

And make sure to add the `deploy_info.json` correctly.

**Comment by quartopianodesign** [comment]
server:project1 alessandromoschetti$ grunt syncdeploy
Running "syncdeploy:main" (syncdeploy) task
Error: No username provided
    at /Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/node-ssh/Dist/SSH.js:39:17
    at SSH.connect (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/node-ssh/Dist/SSH.js:37:14)
    at gruntSyncDeploy (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt-sync-deploy/tasks/syncdeploy.js:44:6)
    at Object.<anonymous> (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt-sync-deploy/tasks/syncdeploy.js:291:3)
    at Object.<anonymous> (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/util/task.js:300:12)
    at /Applications/MAMP/htdocs/testNuovoCms/test_grunt2/project1/node_modules/grunt/lib/util/task.js:227:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

This is my deploy_info.json, the syntax it's correct?
{
    "production": {
      "host": "myHost.it",
      "port": "21",
      "username": "myUsername",
      "password": "myPassword",
      "deployTo": "test"

    }

}
